attrs_all_placeholders_complete = {
    # capture internet from requests
    "try": """
    try:
        print(e)
    except Exception as e:
        print(e)
    """,
    "requests_handle_errors": """
    # elif self.page.route == "/markdown":
    # ---------- capture internet --------------
    response = [False, []]
    try:
        response = self.app.request_get(
            url="http://192.168.44.1:8081/get-table-name/widget-list",
            params=params,
        )

    except Exception as e:
        self.page.session.set("error", {"error": str(e), "page": "/markdown"})
        self.page.go("/error-connection")
    # ---------- capture internet --------------
    # if response[0]:
    #    ...
    """,
    "for_range": "for _ in range(8)",
    "for_list": "for _ in ['demo','list']",
    "on_click_alert": "on_click=lamnbda _: self.page.open(alert)",
    # session preferences
    "save_session_set": "page.session.set('number.setting', 12345),",
    "save_session_get": "page.session.get('key'),",
    "save_session_contains": "page.session.contains_key('key'),",
    "save_session_keys": "page.session.get_keys('key-prefix.'),",
    "save_session_remove": "page.session.remove('key'),",
    "save_session_clear": "page.session.clear(),",
    # share preferences
    "save_storage_set": "page.client_storage.set('number.setting', 12345),",
    "save_storage_get": "page.client_storage.get('key'),",
    "save_storage_contains": "page.client_storage.contains_key('key'),",
    "save_storage_keys": "page.client_storage.get_keys('key-prefix.'),",
    "save_storage_remove": "page.client_storage.remove('key'),",
    "save_storage_clear": "page.client_storage.clear(),",
    # colores y fondo
    "focused_color": "focused_color=ft.Colors.BLUE_900,",
    "focused_bgcolor": "focused_bgcolor=ft.Colors.BLUE_900,",
    "bgcolor": "bgcolor=ft.Colors(ft.Colors.${1:GREY_900}),",
    "bgcolor_with_opacity": "bgcolor=ft.Colors.with_opacity(opacity=0.8,color=ft.Colors(ft.Colors.${1:GREY_900})),",
    "bgcolor_gradient": "bgcolor=ft.LinearGradient(colors=[ft.Colors.${1:BLUE}, ft.Colors.${2:CYAN}]),",
    "image": "image=ft.DecorationImage(src='logo.png',fit=ft.ImageFit.COVER,opacity=0.02),\n# NONE CONTAIN COVER FILL FIT_HEIGHT FIT_WIDTH SCALE_DOWN,",
    "bgimage": "bgimage=ft.Image(src='${1:https://via.placeholder.com/600}'),",
    "color": "color=ft.Colors.${1:WHITE},",
    "color_with_opacity": "color=ft.Colors.with_opacity(opacity=0.8,color=ft.Colors(ft.Colors.${1:GREY_900})),",
    # texto y contenido
    "text": "text='${1:flet-box}',",
    "title": "title=ft.Text('${1:flet-box}'),",
    "content": "content=ft.Text('${1:flet-box}'),",
    "child": "content=${1:ft.Container(content=ft.Text('${2:flet-box}'))},",
    "children": "controls=${1:[ft.Text('${2:flet-box}'), ft.Text('${3:flet-box}')]},",
    "children_controls": "controls=${1:[ft.Text('flet-box') for _ in range(${2:3})]},",
    # tamaño y layout
    "width": "width=${1:200},",
    "height": "height=${1:100},",
    "min_width": "min_width=${1:0},",
    "max_width": "max_width=${1:800},",
    "min_height": "min_height=${1:0},",
    "max_height": "max_height=${1:600},",
    "expand": "expand=${1:True},",
    "flex": "flex=${1:1},",
    "alignment_row_column": "alignment=ft.MainAxisAlignment.SPACE_AROUND,\n# START END CENTER SPACE_BETWEEN SPACE_AROUND SPACE_EVENLY,",
    "alignment_vertical_row": "vertical_alignment=ft.CrossAxisAlignment.CENTER,\n# START END CENTER STRETCH BASELINE,",
    "alignment_horizontal_column": "horizontal_alignment=ft.CrossAxisAlignment.CENTER,\n# START END CENTER STRETCH BASELINE,",
    "alignment": "alignment=ft.alignment.${1:center}\n# top_left,top_center,top_right,center_lef,center,center_righ,bottom_left,bottom_right,bottom_center,",
    "child_aspect_ratio": "child_aspect_ratio=${1:1.0},",
    "scroll": "scroll=ft.ScrollMode.${1:HIDDEN},\n# ADAPTIVE ,AUTO ,HIDDEN ,ALWAYS",
    "spacing": "spacing=${1:8},",
    "gap": "gap=${1:8},",
    # padding / margin (ALL / ONLY / SYMMETRIC / specific)
    "padding_only": "padding=ft.Padding.only(left=${1:0}, top=${2:10}, right=${3:0}, bottom=${4:10}),",
    "margin_only": "margin=ft.Padding.only(left=${1:0}, top=${2:10}, right=${3:0}, bottom=${4:10}),",
    "padding_all": "padding=ft.Padding.all(${1:10}),",
    "margin_all": "margin=ft.Padding.all(${1:10}),",
    "item_padding": "item_padding=ft.Padding.all(${1:6}),",
    "content_padding": "content_padding=ft.Padding.symmetric(horizontal=${1:12}, vertical=${2:8}),",
    "inner_padding": "inner_padding=ft.Padding.only(left=${1:8}, right=${2:8}),",
    # only
    "margin_top": "margin=ft.Padding.only(top=${1:10}),",
    "margin_bottom": "margin=ft.Padding.only(bottom=${1:10}),",
    "margin_left": "margin=ft.Padding.only(left=${1:10}),",
    "margin_right": "margin=ft.Padding.only(right=${1:10}),",
    "padding_top": "padding=ft.Padding.only(top=${1:10}),",
    "padding_bottom": "padding=ft.Padding.only(bottom=${1:10}),",
    "padding_left": "padding=ft.Padding.only(left=${1:10}),",
    "padding_right": "padding=ft.Padding.only(right=${1:10}),",
    "margin_symmetric": "margin=ft.Padding.symmetric(horizontal=${1:8}, vertical=${2:12}),",
    "padding_symmetric": "padding=ft.Padding.symmetric(horizontal=${1:8}, vertical=${2:12}),",
    "margin_horizontal": "margin=ft.Padding.symmetric(horizontal=${1:8}),",
    "margin_vertical": "margin=ft.Padding.symmetric(vertical=${1:12}),",
    "padding_horizontal": "padding=ft.Padding.symmetric(horizontal=${1:8}),",
    "padding_vertical": "padding=ft.Padding.symmetric(vertical=${1:12}),",
    # bordes, sombra y estética
    "border": "border=ft.border.all(${1:1}, ft.Colors.${2:BLACK12}),",
    "border_width": "border_width=${1:1},",
    "border_color": "border_color=ft.Colors.${2:GREY_800}),",
    "border_radius_all": "border_radius=ft.BorderRadius.all(32),",
    "border_radius_only": "border_radius=ft.BorderRadius.only(top_left=8,top_right=8,bottom_left=8,bottom_right=8),",
    "shadow": "shadow=ft.BoxShadow(spread_radius=1,blur_radius=15,color=ft.Colors.BLACK,offset=ft.Offset(0,0),blur_style=ft.ShadowBlurStyle.OUTER,),",
    "shadow_color": "shadow=ft.Shadow(offset=ft.Offset(${1:2}, ${2:2}), blur=${3:6}, color=ft.Colors.${4:GREY_500}),",
    "bg_opacity": "opacity=${1:0.8},",
    "gradient": "gradient=ft.LinearGradient(begin=ft.alignment.top_center,end=ft.alignment.bottom_center,colors=[ft.Colors.TRANSPARENT,ft.Colors.BLACK12,],),",
    # iconografía y multimedia
    "icon": "icon=ft.Icons(ft.Icon(ft.icons.${1:INFO})),",
    "icon_only": "icon=ft.Icons(ft.Icon(ft.icons.${1:ADD})),",
    "leading": "leading=ft.Icon(ft.icons.${1:PERSON}),",
    "trailing": "trailing=ft.Icon(ft.icons.${1:CHECK}),",
    "src": "src='${1:https://via.placeholder.com/150}',",
    "fit": "fit='${1:contain}',",
    "fit_mode": "fit='${1:contain}',",
    "autoplay": "autoplay=${1:False},",
    "autoplay_lottie": "autoplay=${1:False},",
    "poster": "poster='${1:https://via.placeholder.com/320x180}',",
    "javascript_enabled": "javascript_enabled=${1:True},",
    "cache": "cache=${1:True},",
    "preload": "preload=${1:False},",
    "poster_image": "poster='${1:https://via.placeholder.com/320x180}',",
    # valores, opciones y datos
    "value": "value=${1:False},",
    "values": "values=${1:(10, 90)},",
    "min": "min=${1:0},",
    "max": "max=${1:100},",
    "value_range": "min=${1:0}, max=${2:100}, value=${3:50},",
    "checked": "value=${1:True},",
    "hint_text": "hint_text='${1:flet-box}',",
    "label": "label='${1:flet-box}',",
    "label_style": "label_style=ft.TextStyle( weight=ft.FontWeight.BOLD, size=18,),",
    "placeholder": "hint_text='${1:flet-box}',",
    "options": 'options=${1:["flet-box,","op2,","op3"]}',
    "selected_index": "selected_index=${1:0},",
    "data": "data=${1:[10,20,30]},",
    "labels": 'labels=${1:["A,","B,","C"]}',
    "points": "points=${1:[(1,2),(2,3),(3,1)]},",
    "max_items": "max_items=${1:10},",
    "min_items": "min_items=${1:0},",
    # texto y tipografía
    "style": "ft.TextStyle(decoration=ft.TextDecoration.${1:UNDERLINE}),\n# OVERLINE, UNDERLINE, LINE_THROUGH,",
    "spans": "[ ft.TextSpan('here goes italic', ft.TextStyle(italic=True, size=20, color=ft.Colors.${1:BLUE}),), ],",
    "theme_style": "theme_style=ft.TextThemeStyle.${1:DISPLAY_LARGE},",
    "italic": "italic=${1:True},",
    "font_size": "size=${1:14},",
    "font_family": "font_family='${1:Roboto}',",
    "font_weight": "weight=ft.FontWeight.${1:NORMAL},",
    "text_align": "text_align=ft.TextAlign.${1:LEFT},",
    "overflow": "overflow=ft.TextOverflow.${1:ELLIPSIS},",
    "max_lines": "max_lines=${1:3},",
    "min_lines": "min_lines=${1:1},",
    "wrap": "wrap=${1:True},",
    # gráficos y trazado
    "stroke_width": "stroke_width=${1:2},",
    "stroke_color": "color=ft.Colors.${1:BLACK},",
    "blur": "blur=${1:6},",
    "offset": "offset=ft.Offset(${1:2}, ${2:2}),",
    # animación y transición
    "animate": "animate=${1:True},",
    "animation_duration": "animation_duration=${1:300},",
    "animation_curve": "animation_curve=ft.AnimationCurve.${1:EASE_IN_OUT},",
    "transition": "transition=${1:None},",
    "easing": "duration=${1:300}, transition=ft.AnimatedSwitcherTransitionType.${2:SCALE},",
    "easing_curve": "curve=ft.AnimationCurve.${1:EASE_IN_OUT},",
    # eventos e interactividad
    "on_click": "on_click=lambda e: print('${1:flet-box}'),",
    "on_change": "on_change=lambda e: print('${1:flet-box}'),",
    "on_dismiss": "on_dismiss=lambda e: print('${1:flet-box}'),",
    "on_hover": "on_hover=lambda e: print('${1:hovered}'),",
    "on_long_press": "on_long_press=lambda e: print('${1:long_press}'),",
    "on_double_tap": "on_double_tap=lambda e: print('${1:double_tap}'),",
    "on_tap": "on_tap=lambda e: print('${1:tapped}'),",
    "on_submit": "on_submit=lambda e: print('${1:submitted}'),",
    "on_drop": "on_drop=lambda e: print('${1:dropped}'),",
    "on_accept": "on_accept=lambda data: print('${1:accepted}'),",
    "on_selected": "on_selected=lambda e: print('${1:selected}'),",
    "on_screenshot": "on_screenshot=lambda e: print('${1:screenshot}'),",
    # validación y binding
    "validator": "validator=lambda v: ${1:True}  # return True/False or error string,",
    "value_binding": "value_binding=${1:my_binding},",
    "format": "format='${1:%Y-%m-%d}',",
    # accesibilidad y estado
    "tooltip": "tooltip='${1:flet-box}',",
    "aria_label": "aria_label='${1:description}',",
    "tab_index": "tab_index=${1:0},",
    "enabled": "enabled=${1:True},",
    "visible": "visible=${1:True},",
    "readonly": "readonly=${1:False},",
    "selectable": "selectable=${1:True},",
    "open": "open=${1:True},",
    "open_on_start": "open=${1:True},",
    "disabled": "disabled=${1:True},",
    # mapas y geolocalización
    "location": "location=(${1:23.1136}, ${2:-82.3666}),",
    "url_template": "url_template='${1:https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png}',",
    "tile_options": "tile_options={'maxZoom':${1:18}},",
    "cluster": "cluster=${1:True},",
    "draggable_marker": "draggable_marker=${1:True},",
    "marker_radius": "radius=${1:5},",
    "map_type": "map_type='${1:streets}',",
    "marker_content": "content=ft.Text('${1:flet-box}'),",
    # gráficos avanzados
    "figure": "figure=${1:None}, width=${2:400}, height=${3:300},",
    "plotly_figure": "figure=${1:None}, width=${2:400}, height=${3:300},",
    "matplotlib_figure": "figure=${1:None}, width=${2:400}, height=${3:300},",
    # misc / utilidades
    "feedback": "feedback=ft.Text('${1:dragging}'),",
    "draggable": "draggable=${1:False},",
    "drop_target": "on_drop=lambda e: print('${1:dropped}'),",
    "readonly_mode": "readonly=${1:False},",
    "cache_policy": "cache=${1:True},",
    "preload_resources": "preload=${1:False},",
    "aria_role": "aria_role='${1:button}',",
    "data_testid": "data_testid='${1:test-id}',",
    "custom_style": "style=${1:ft.ButtonStyle(color=ft.Colors.${2:BLUE})},",
    "extra": "extra=${1:None},",
}
